create table public.app_versions (
  id bigint generated by default as identity primary key,
  version text not null, -- contoh: '1.02'
  download_url text not null, -- link download apk
  force_update boolean default false,
  release_notes text, -- KATA KATA/PESAN UPDATE DISINI
  created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

-- Enable RLS (Recommended)
alter table public.app_versions enable row level security;

-- Create policy to allow public read access
create policy "App versions are viewable by everyone"
  on public.app_versions for select
  using ( true );

-- Create policy to allow authenticated users (or admins) to insert/update
-- Adjust this based on your auth requirements. For now, allowing all authenticated users to edit might be risky if you have public signups.
-- create policy "Authenticated users can insert app versions"
--   on public.app_versions for insert
--   with check ( auth.role() = 'authenticated' );

-- Contoh insert data:
-- insert into public.app_versions (version, download_url, release_notes) 
-- values ('1.02', 'https://...', 'Update baru: Perbaikan bug dan fitur offline!');
